# map 地图
#    --> y 
#   |
#   |
#   x
[mapdata]
map = [
    [1, 1, 1, 1, 1, 1, 1, 1], 
    [1, 0, 0, 0, 0, 0, 0, 1], 
    [1, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 0, 0, 0]
]
# 目标
target = [
    {x = 1, y = 1}, 
    {x = 1, y = 3}, 
    {x = 1, y = 5},
]

[initstep]
player = {x = 2, y = 5}
box = [
    {x = 2, y = 2}, 
    {x = 2, y = 4}, 
    {x = 1, y = 4}
]
